### ISSUE TITLE
build failed, need DOCKER_HOST 

### ISSUE THREAD

**Issue by yeganx** [davsclaus/fabric8-hello#1]
hi 
I have problem in build docker image .
if i use maven-plugin for fabric 8 do I need install docker ?
i just do like below 
 $mvn io.fabric8:fabric8-maven-plugin:3.1.74:cluster-start
that was run correct and i have fabric8 console in http://192.168.99.101:31938
but in this step ,give  error  : 
$cd client
$mvn install
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.74:build (fmp) on project client: Execution fmp of goal io.fabric8:fabric8-maven-plugin:3.1.74:build failed: No <dockerHost> given, no DOCKER_HOST environment variable, no read/writable '/var/run/docker.sock' or '//./pipe/docker_engine' and no external provider like Docker machine configured -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
and i dont know what i should set for DOCKER_HOST ?!

**Comment by davsclaus** [comment]
Ah sorry for the delay, the f-m-p plugin has been improved in newer releases where it can autodetect your cluster better and DOCKER_HOST etc.

**Comment by davsclaus** [comment]
What you need to do is to set your shell to have the ENV for docker so it can connect to docker, you can do this with

gofabric8 docker-env

And then run that eval command it outputs.

However newer version of fmp plugin should auto do this if it can

**Comment by davsclaus** [comment]
For example with latest f-m-p version (source has been updated) then the plugin uses gofabric8 to get that docker host and I dont need to do anything

```
[INFO] --- fabric8-maven-plugin:3.1.92:build (fmp) @ helloswarm ---
[INFO] F8: Building Docker image in Kubernetes mode
[INFO] F8: Running generator wildfly-swarm
[INFO] F8: DOCKER_HOST from gofabric8 : tcp://192.168.64.20:2376
[INFO] F8: Pulling from fabric8/java-alpine-openjdk8-jdk
```
